apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: vishrut0/project:app
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: DB_PASSWORD
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: AWS_REGION
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: S3_BUCKET
        - name: SQS_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: SQS_QUEUE_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: DB_NAME
